### ISSUE TITLE
TITLE: Mod 0 Assessment Feedback 

### ISSUE THREAD

**Issue by jeremiahblackol** [clairefields15/mod_0_skills#1]
I only noticed one thing that I want you to look at, and that is putting all your data as strings. I wasn't sure if that was you intention, but I pointed it out in the feedback. Congrats! Completed and technical ready. Great job Continue asking questions in class, and being active in your cohort slack channel!

## Part 1
 - has repository named `mod_0_skills` and `variables.txt`
 - first commit is titles `Initial commit`

## Part 2
 - good work here, did you intend for `var isEntertaining = 'TRUE'` to be boolean, or was it supposed to be set to the string.
 - `var char = movie.length` nothing wrong with the variable name technically, I'm assuming `char` is short for characters in a string. I think it's more empathetic to other developers to name it `var numberOfCharacters` or something more descriptive.
 - has commit: "Complete program specific challenge"
 
## Part 3

- file structure matches the directions
- methods modify or use attributes
- `costOfLatte = '4.57', changePrice: costOfLatte = '4.99'` do you want those prices to be strings?
- naming conventions are clear
- good use of camelCase!

**Comment by clairefields15** [comment]
Ah, no, I definitely did not mean to do that. I will go back and make those changes. Thanks! I have a lot to review and retain, but psyched to get started for real!
